[package]
name = "btreemap"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
derive_more = {version = "1.0.0-beta.6", features = ["into_iterator"]}
